apiVersion: pmp.io/v1
kind: Template
metadata:
  name: helm-application
  description: Deploy Helm charts using ArgoCD Application

spec:
  apiVersion: pmp.io/v1
  kind: KubernetesWorkload
  executor: opentofu

  inputs:
    - name: project
      default: "default"
      description: ArgoCD project name
    - name: app_description
      default: ""
      description: Description of the application (optional)
    - name: helm_repo_url
      default: "https://comfortablynumb.github.io/pmp-helm-charts"
      description: Helm repository URL
    - name: chart_name
      default: "charts/application"
      description: Name of the Helm chart in the repository
    - name: target_revision
      default: ""
      description: Chart version to deploy (required)
      required: true
    - name: helm_release_name
      default: ""
      description: Helm release name (optional, defaults to project name)
    - name: helm_values
      default: ""
      description: Inline Helm values as YAML string (optional)
    - name: helm_values_files
      default: ""
      description: Comma-separated list of values file paths in the repo (optional)
    - name: helm_parameters
      default: ""
      description: Helm parameters as key=value pairs, comma-separated (optional)
    - name: destination_namespace
      default: "default"
      description: Target Kubernetes namespace for deployment
    - name: destination_server
      default: "https://kubernetes.default.svc"
      description: Target Kubernetes cluster API server URL

  dependencies:
    - project:
        apiVersion: pmp.io/v1
        kind: KubernetesWorkload
        label_selector:
          pmp.io/project-type: application
          pmp.io/project-vendor: argo-cd
        remote_state:
          data_source_name: argocd_instance

  environments: {}
