apiVersion: pmp.io/v1
kind: Template
metadata:
  name: http-api
  description: Deploy an HTTP API service on Kubernetes with auto-scaling, health checks, and database plugin support

spec:
  apiVersion: pmp.io/v1
  kind: KubernetesWorkload
  executor: opentofu

  plugins:
    allowed:
      - template_pack_name: postgres
        plugin_name: access
        inputs:
          - name: k8s_secret_namespace
            default: ""
            description: Kubernetes namespace for credential secret (defaults to project namespace)
      - template_pack_name: vault
        plugin_name: secret

    # Example: Plugins that are automatically installed during project creation
    # Uncomment to enable auto-provisioning of GitHub repository and ECR registry
    # installed:
    #   - template_pack_name: github
    #     plugin_name: repository
    #     inputs:
    #       - name: gitignore_template
    #         default: Terraform
    #       - name: license_template
    #         default: apache-2.0
    #       - name: visibility
    #         default: private
    #   - template_pack_name: aws
    #     plugin_name: ecr
    #     inputs:
    #       - name: image_tag_mutability
    #         default: IMMUTABLE
    #       - name: scan_on_push
    #         default: "true"

  inputs:
    - name: docker_image
      description: Docker image name (e.g., nginx, myregistry.io/myapp)
    - name: docker_image_version
      description: Docker image tag/version (e.g., latest, v1.2.3)
      default: latest
    - name: min_replicas
      default: 2
      description: Minimum number of pod replicas for auto-scaling
    - name: max_replicas
      default: 10
      description: Maximum number of pod replicas for auto-scaling
    - name: cpu_millicores
      enum_values:
        - 20
        - 50
        - 100
        - 250
        - 500
        - 1000
        - 1500
        - 2000
        - 4000
        - 6000
        - 8000
        - 16000
        - 32000
      default: 250
      description: CPU limit in millicores (1000m = 1 CPU core)
    - name: memory_mb
      enum_values:
        - 64
        - 128
        - 256
        - 512
        - 1024
        - 2048
        - 4096
        - 8192
        - 16384
      default: 512
      description: Memory limit in MB
    - name: http_port
      default: 8080
      description: Container HTTP port to expose
    - name: healthcheck_uri
      default: "/_/health"
      description: HTTP path for health check endpoint
    - name: service_type
      enum_values:
        - ClusterIP
        - NodePort
        - LoadBalancer
      default: ClusterIP
      description: Kubernetes service type (ClusterIP for internal, NodePort for development, LoadBalancer for production)

  environments: {}
