apiVersion: pmp.io/v1
kind: Template
metadata:
  name: repository
  description: Create and manage a GitHub repository with comprehensive configuration options

spec:
  apiVersion: pmp.io/v1
  kind: CodeRepository
  executor: opentofu

  # Example: Plugins that are automatically installed during project creation
  # Uncomment to enable auto-provisioning of resources for this repository
  # plugins:
  #   installed:
  #     - template_pack_name: aws
  #       plugin_name: ecr
  #       inputs:
  #         image_tag_mutability:
  #           default: IMMUTABLE
  #         scan_on_push:
  #           default: "true"

  inputs:
    # Basic Settings
    repository_name:
      type: string
      description: Repository name (must be unique within your organization/account)

    description:
      type: string
      description: Repository description
      default: ""

    visibility:
      type: select
      options:
        - label: "Public (Anyone can see)"
          value: "public"
        - label: "Private (Only you and collaborators)"
          value: "private"
        - label: "Internal (Organization members only)"
          value: "internal"
      default: "private"
      description: Repository visibility level

    homepage_url:
      type: string
      description: Repository homepage URL
      default: ""

    # Repository Features
    has_issues:
      type: boolean
      description: Enable issues for this repository
      default: true

    has_wiki:
      type: boolean
      description: Enable wiki for this repository
      default: false

    has_projects:
      type: boolean
      description: Enable projects for this repository
      default: false

    has_discussions:
      type: boolean
      description: Enable discussions for this repository
      default: false

    has_downloads:
      type: boolean
      description: Enable downloads feature for this repository
      default: true

    # Initialization Options
    auto_init:
      type: boolean
      description: Initialize repository with README file
      default: true

    gitignore_template:
      type: select
      options:
        - label: "None"
          value: ""
        - label: "Node.js"
          value: "Node"
        - label: "Python"
          value: "Python"
        - label: "Go"
          value: "Go"
        - label: "Rust"
          value: "Rust"
        - label: "Java"
          value: "Java"
        - label: "Ruby"
          value: "Ruby"
        - label: "Terraform"
          value: "Terraform"
        - label: "Visual Studio"
          value: "VisualStudio"
        - label: "VS Code"
          value: "VisualStudioCode"
        - label: "JetBrains IDEs"
          value: "JetBrains"
        - label: "Vim"
          value: "Vim"
      default: ""
      description: .gitignore template to use

    license_template:
      type: select
      options:
        - label: "None"
          value: ""
        - label: "MIT License"
          value: "mit"
        - label: "Apache License 2.0"
          value: "apache-2.0"
        - label: "GNU GPL v3.0"
          value: "gpl-3.0"
        - label: "BSD 2-Clause License"
          value: "bsd-2-clause"
        - label: "BSD 3-Clause License"
          value: "bsd-3-clause"
        - label: "Mozilla Public License 2.0"
          value: "mpl-2.0"
        - label: "GNU LGPL v3.0"
          value: "lgpl-3.0"
        - label: "GNU AGPL v3.0"
          value: "agpl-3.0"
        - label: "The Unlicense"
          value: "unlicense"
      default: ""
      description: License template to use

    default_branch:
      type: string
      description: Default branch name
      default: "main"

    # Merge Settings
    allow_merge_commit:
      type: boolean
      description: Allow merge commits
      default: true

    allow_squash_merge:
      type: boolean
      description: Allow squash merging
      default: true

    allow_rebase_merge:
      type: boolean
      description: Allow rebase merging
      default: true

    allow_auto_merge:
      type: boolean
      description: Allow auto-merge on pull requests
      default: false

    delete_branch_on_merge:
      type: boolean
      description: Automatically delete head branches after pull requests are merged
      default: true

    # Topics and Metadata
    topics:
      type: string
      description: Repository topics (comma-separated, lowercase, use hyphens)
      default: ""

    is_template:
      type: boolean
      description: Mark this repository as a template repository
      default: false

    archived:
      type: boolean
      description: Archive this repository (read-only)
      default: false

    # Security Settings
    vulnerability_alerts:
      type: boolean
      description: Enable security vulnerability alerts
      default: true

    # Branch Protection
    enable_branch_protection:
      type: boolean
      description: Enable branch protection rules for the default branch
      default: false

    require_pull_request_reviews:
      type: boolean
      description: Require pull request reviews before merging
      default: true

    required_approving_review_count:
      type: select
      options:
        - label: "1 Approval"
          value: "1"
        - label: "2 Approvals"
          value: "2"
        - label: "3 Approvals"
          value: "3"
        - label: "4 Approvals"
          value: "4"
        - label: "5 Approvals"
          value: "5"
        - label: "6 Approvals"
          value: "6"
      default: "1"
      description: Number of required approving reviews

    require_code_owner_reviews:
      type: boolean
      description: Require review from code owners
      default: false

    dismiss_stale_reviews:
      type: boolean
      description: Dismiss stale pull request reviews when new commits are pushed
      default: true

    require_status_checks:
      type: boolean
      description: Require status checks to pass before merging
      default: false

    status_check_contexts:
      type: string
      description: Required status check contexts (comma-separated)
      default: ""

    enforce_admins:
      type: boolean
      description: Enforce branch protection rules for administrators
      default: false

    require_signed_commits:
      type: boolean
      description: Require signed commits
      default: false

    require_linear_history:
      type: boolean
      description: Require linear history (no merge commits)
      default: false

    # Access Management
    enable_team_access:
      type: boolean
      description: Enable team-based access management
      default: false

    teams:
      type: string
      description: Team access configuration (format - team-name:permission,another-team:permission)
      default: ""

    enable_collaborator_access:
      type: boolean
      description: Enable individual collaborator access management
      default: false

    collaborators:
      type: string
      description: Collaborator access configuration (format - username:permission,another-user:permission)
      default: ""

  environments: {}
