apiVersion: pmp.io/v1
kind: Template
metadata:
  name: "Kubernetes Workload"
  description: "Creates a simple Kubernetes workload"
spec:
  resource:
    apiVersion: pmp.io/v1
    kind: Workload
    iac:
      provider: opentofu
    # Inputs applied to all environments
    inputs:
      instance_type:
        enum_values: [ "t3.micro", "t3.small" ]
        default: "t3.micro"
        description: "EC2 instance type (development options)"
      replicas:
        default: 1
      enable_monitoring:
        default: true
    environments:
      production:
        overrides:
          # Each input defined here overrides the ones at $.spec.resource.inputs
          # for this environment
          inputs:
            instance_type:
              enum_values: [ "t3.medium", "t3.large", "t3.xlarge" ]
              default: "t3.medium"
              description: "EC2 instance type (production options)"
            replicas:
              default: 3