apiVersion: pmp.io/v1
kind: Template
metadata:
  name: ecr
  description: Create and manage AWS ECR (Elastic Container Registry) repositories for Docker images

spec:
  apiVersion: pmp.io/v1
  kind: ContainerRegistry
  executor: opentofu

  inputs:
    # Basic Settings
    repository_name:
      type: string
      description: ECR repository name (must be unique within AWS account and region)

    image_tag_mutability:
      type: select
      options:
        - label: "Mutable (Tags can be overwritten)"
          value: "MUTABLE"
        - label: "Immutable (Tags are permanent)"
          value: "IMMUTABLE"
      default: "MUTABLE"
      description: Tag mutability setting for the repository

    force_delete:
      type: boolean
      description: Allow repository deletion even if it contains images
      default: false

    # Encryption Settings
    encryption_type:
      type: select
      options:
        - label: "AES256 (AWS Managed)"
          value: "AES256"
        - label: "KMS (Customer Managed)"
          value: "KMS"
      default: "AES256"
      description: Encryption type for images at rest

    kms_key_arn:
      type: string
      description: ARN of KMS key for encryption (only used when encryption_type is KMS)
      default: ""

    enable_kms_key_rotation:
      type: boolean
      description: Enable automatic key rotation for KMS keys (only when no custom KMS key is provided)
      default: true

    # Image Scanning
    scan_on_push:
      type: boolean
      description: Enable automatic image scanning when images are pushed
      default: true

    # Lifecycle Policy Settings
    enable_lifecycle_policy:
      type: boolean
      description: Enable lifecycle policy to automatically clean up old images
      default: true

    keep_image_count:
      type: select
      options:
        - label: "5 images"
          value: "5"
        - label: "10 images"
          value: "10"
        - label: "15 images"
          value: "15"
        - label: "20 images"
          value: "20"
        - label: "30 images"
          value: "30"
        - label: "50 images"
          value: "50"
      default: "10"
      description: Number of tagged images to retain (for lifecycle policy)

    lifecycle_tag_prefix:
      type: string
      description: Tag prefix for lifecycle policy rules (e.g., 'v' for v1.0.0, v1.1.0)
      default: "v"

    lifecycle_tag_status:
      type: select
      options:
        - label: "Tagged only"
          value: "tagged"
        - label: "Untagged only"
          value: "untagged"
        - label: "Any (both tagged and untagged)"
          value: "any"
      default: "tagged"
      description: Apply lifecycle rules to which tag types

    expire_untagged_after_days:
      type: select
      options:
        - label: "1 day"
          value: "1"
        - label: "3 days"
          value: "3"
        - label: "7 days"
          value: "7"
        - label: "14 days"
          value: "14"
        - label: "30 days"
          value: "30"
      default: "7"
      description: Number of days to keep untagged images before expiring them

    # Repository Policy Settings
    enable_repository_policy:
      type: boolean
      description: Enable repository policy for cross-account or IAM-based access
      default: false

    allowed_aws_account_ids:
      type: string
      description: Comma-separated list of AWS account IDs allowed to pull images (requires enable_repository_policy)
      default: ""

    allowed_iam_arns:
      type: string
      description: Comma-separated list of IAM ARNs allowed to access repository (requires enable_repository_policy)
      default: ""

    # Tagging
    repository_tags:
      type: string
      description: Repository tags as comma-separated key:value pairs (e.g., Environment:prod,Team:platform)
      default: ""

  environments: {}
