apiVersion: pmp.io/v1
kind: Template
metadata:
  name: postgres
  description: PostgreSQL database deployment with Bitnami Helm chart

spec:
  apiVersion: pmp.io/v1
  kind: Postgres
  executor: opentofu

  inputs:
    - name: namespace
      type: string
      default: "postgres"
      description: Kubernetes namespace for PostgreSQL
    - name: chart_version
      type: string
      default: "15.5.38"
      description: Bitnami PostgreSQL Helm chart version
    - name: create_namespace
      type: boolean
      default: true
      description: Whether to create the namespace if it doesn't exist
    - name: database_name
      type: string
      default: "mydb"
      description: Name of the PostgreSQL database to create
    - name: postgres_username
      type: string
      default: "postgres"
      description: PostgreSQL superuser username
    - name: postgres_password
      type: string
      default: "changeme123"
      description: PostgreSQL superuser password (CHANGE IN PRODUCTION!)
    - name: storage_size
      type: string
      default: "8Gi"
      description: Size of the persistent volume for database data
    - name: storage_class
      type: string
      default: ""
      description: Storage class name for persistence (empty for default)
    - name: persistence_enabled
      type: boolean
      default: true
      description: Enable persistent storage for database data
    - name: architecture
      type: select
      options:
        - label: "Standalone (Single Instance)"
          value: "standalone"
        - label: "Replication (Primary + Replicas)"
          value: "replication"
      default: "standalone"
      description: PostgreSQL architecture
    - name: replica_count
      type: number
      min: 1
      max: 10
      default: 1
      description: Number of read replicas (only for replication mode)
    - name: resources_requests_cpu
      type: string
      default: "250m"
      description: CPU resource request for PostgreSQL
    - name: resources_requests_memory
      type: string
      default: "256Mi"
      description: Memory resource request for PostgreSQL
    - name: resources_limits_cpu
      type: string
      default: "500m"
      description: CPU resource limit for PostgreSQL
    - name: resources_limits_memory
      type: string
      default: "512Mi"
      description: Memory resource limit for PostgreSQL
    - name: metrics_enabled
      type: boolean
      default: false
      description: Enable Prometheus metrics exporter
    - name: service_type
      type: select
      options:
        - label: "ClusterIP (Internal Only)"
          value: "ClusterIP"
        - label: "LoadBalancer (External Access)"
          value: "LoadBalancer"
        - label: "NodePort (Node Port Access)"
          value: "NodePort"
      default: "ClusterIP"
      description: Kubernetes service type for PostgreSQL
    - name: sslmode
      type: select
      options:
        - label: "Disable (No SSL)"
          value: "disable"
        - label: "Prefer (SSL if available)"
          value: "prefer"
        - label: "Require (SSL required)"
          value: "require"
      default: "prefer"
      description: PostgreSQL SSL mode for client connections
