apiVersion: pmp.io/v1
kind: Template
metadata:
  name: argo-cd
  description: Basic Argo CD installation with Helm
  labels:
    pmp.io/project-type: application
    pmp.io/project-vendor: argo-cd
spec:
  apiVersion: pmp.io/v1
  kind: KubernetesWorkload
  executor: opentofu

  inputs:
    - name: namespace
      default: "argocd"
      description: Kubernetes namespace for Argo CD
    - name: chart_version
      default: "5.51.6"
      description: Argo CD Helm chart version
    - name: create_namespace
      default: true
      description: Whether to create the namespace if it doesn't exist
    - name: server_host
      default: ""
      description: Hostname for Argo CD server (optional, for ingress)
    - name: enable_ingress
      default: false
      description: Enable ingress for Argo CD server
    - name: ingress_class
      default: "nginx"
      description: Ingress class name
    - name: admin_password
      default: ""
      description: Admin password (leave empty for auto-generated)
    - name: server_replicas
      default: 1
      description: Number of Argo CD server replicas
    - name: repo_server_replicas
      default: 1
      description: Number of Argo CD repo-server replicas
    - name: ha_enabled
      default: false
      description: Enable high availability mode
