apiVersion: pmp.io/v1
kind: Infrastructure
metadata:
  name: Infrastructure Project Example
  description: This example project demonstrates all the functionalities found on PMP
spec:
  categories:
    - id: applications
      name: Applications
      description: Application workloads and services
      subcategories:
        - id: applications_argocd
          name: ArgoCD Applications
          description: Applications deployed with ArgoCD
          subcategories: []
          templates:
            - template_pack: argo-cd
              template: helm-application
      templates: []
    - id: platform-services
      name: Platform Services
      description: Core platform services and utilities
      subcategories:
        - id: platform-deployment-tools
          name: Deployment Tools
          description: Tools that simplify the deployment of applications
          subcategories:
            - id: platform-deployment-tools-argo-cd
              name: ArgoCD
              description: ArgoCD + Related Templates
              subcategories: [ ]
              templates:
                - template_pack: argo-cd
                  template: argo-cd
                - template_pack: argo-cd
                  template: argo-cd-core-configuration
        - id: platform-ingresses
          name: Kubernetes Ingresses
          description: Ingresses for Kubernetes
          subcategories:
            - id: platform-ingresses
              name: Istio
              description: Istio Ingress
              subcategories: [ ]
              templates:
                - template_pack: kubernetes
                  template: istio-ingress-controller
        - id: platform-secrets-managers
          name: Secrets Managers
          description: Tools that allow to manage secrets
          subcategories:
            - id: platform-secrets-managers-vault
              name: Vault
              description: Vault + Related Templates
              subcategories: [ ]
              templates:
                - template_pack: vault
                  template: vault
                - template_pack: vault
                  template: vault-core-configuration
  template_packs:
    postgres:
      templates:
        postgres:
          defaults:
            inputs:
              instance_name:
                value: main-db
                show_as_default: true
    github:
      templates:
        repository:
          defaults:
            inputs:
              visibility:
                value: private
                show_as_default: true
    minikube-http-echo:
      templates:
        minikube-http-echo:
          defaults:
            inputs: {}
    examples:
      templates:
        application:
          defaults:
            inputs: {}
    kubernetes:
      templates:
        k8s-monitoring:
          defaults:
            inputs: {}
        linkerd:
          defaults:
            inputs: {}
    vault:
      templates:
        vault:
          defaults:
            inputs: {}
    kubernetes-workloads:
      templates:
        helm:
          defaults:
            inputs: {}
        http-api:
          defaults:
            inputs:
              version:
                value: latest
                show_as_default: false
              docker_image:
                value: ironedge/pmp-test-api
                show_as_default: false
    argo-cd:
      templates:
        argo-cd:
          defaults:
            inputs:
              namespace:
                value: argocd
                show_as_default: true
        helm-application:
          defaults:
            inputs: {}
    aws:
      templates:
        ecr:
          defaults:
            inputs:
              image_tag_mutability:
                value: MUTABLE
                show_as_default: true
  environments:
    staging:
      name: Staging
      description: Pre-production environment for final validation
    production:
      name: Production
      description: Production environment with high availability
    development:
      name: Development
      description: Development environment for testing and iteration
  hooks: null
  executor:
    name: opentofu
    config:
      backend:
        conn_str: postgres://terraform:terraform@localhost:5432/terraform_backend?sslmode=disable
        schema_name: terraform_remote_state
        type: pg
