apiVersion: pmp.io/v1
kind: Infrastructure
metadata:
  name: Infrastructure Project Example
  description: This example project demonstrates all the functionalities found on PMP
spec:
  categories:
  - id: applications
    name: Applications
    description: Application workloads and services
    subcategories:
    - id: applications_gitops
      name: GitOps
      description: GitOps and continuous deployment tools
      subcategories: []
      templates:
      - template_pack: argo-cd
        template: argo-cd
      - template_pack: argo-cd
        template: helm-application
    - id: applications_microservices
      name: Microservices
      description: Microservices and API applications
      subcategories: []
      templates:
      - template_pack: examples
        template: application
    - id: applications_platform
      name: Platform Services
      description: Core platform services and utilities
      subcategories: []
      templates:
      - template_pack: kubernetes-workloads
        template: helm
      - template_pack: vault
        template: vault
    - id: applications_development
      name: Development & Testing
      description: Development and testing applications
      subcategories: []
      templates:
      - template_pack: minikube-http-echo
        template: minikube-http-echo
    templates: []
  - id: infrastructure
    name: Infrastructure
    description: Core infrastructure components and services
    subcategories:
    - id: infrastructure_databases
      name: Databases
      description: Database systems and data stores
      subcategories: []
      templates:
      - template_pack: postgres
        template: postgres
    - id: infrastructure_networking
      name: Networking
      description: Service mesh and networking components
      subcategories: []
      templates:
      - template_pack: kubernetes
        template: linkerd
    - id: infrastructure_observability
      name: Observability
      description: Monitoring, logging, and tracing
      subcategories: []
      templates:
      - template_pack: kubernetes
        template: k8s-monitoring
    templates: []
  - id: devops
    name: DevOps
    description: Development and operations tools
    subcategories:
    - id: devops_source_control
      name: Source Control
      description: Version control repositories
      subcategories: []
      templates:
      - template_pack: github
        template: repository
    - id: devops_registries
      name: Container Registries
      description: Container image registries
      subcategories: []
      templates:
      - template_pack: aws
        template: ecr
    templates: []
  template_packs:
    postgres:
      templates:
        postgres:
          defaults:
            inputs:
              instance_name:
                value: main-db
                show_as_default: true
    github:
      templates:
        repository:
          defaults:
            inputs:
              visibility:
                value: private
                show_as_default: true
    minikube-http-echo:
      templates:
        minikube-http-echo:
          defaults:
            inputs: {}
    examples:
      templates:
        application:
          defaults:
            inputs: {}
    kubernetes:
      templates:
        k8s-monitoring:
          defaults:
            inputs: {}
        linkerd:
          defaults:
            inputs: {}
    vault:
      templates:
        vault:
          defaults:
            inputs: {}
    kubernetes-workloads:
      templates:
        helm:
          defaults:
            inputs: {}
        http-api:
          defaults:
            inputs:
              version:
                value: latest
                show_as_default: false
              docker_image:
                value: ironedge/pmp-test-api
                show_as_default: false
    argo-cd:
      templates:
        argo-cd:
          defaults:
            inputs:
              namespace:
                value: argocd
                show_as_default: true
        helm-application:
          defaults:
            inputs: {}
    aws:
      templates:
        ecr:
          defaults:
            inputs:
              image_tag_mutability:
                value: MUTABLE
                show_as_default: true
  environments:
    staging:
      name: Staging
      description: Pre-production environment for final validation
    production:
      name: Production
      description: Production environment with high availability
    development:
      name: Development
      description: Development environment for testing and iteration
  hooks: null
  executor:
    name: opentofu
    config:
      backend:
        conn_str: postgres://terraform:terraform@localhost:5432/terraform_backend?sslmode=disable
        schema_name: terraform_remote_state
        type: pg
